config/routes.rb
Rails.application.routes.draw do
  get 'email_links/new'
  get 'email_links/validate', as: :email_link
  post 'email_links/create', as: :send_link
  devise_for :users
  root "main#welcome"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_link.rb
class EmailLink < ApplicationRecord
  belongs_to :user
  after_create :send_mail

  def self.generate(email)
  	user = User.find_by(email: email)
  	return nil if !user

  	# Date.today envia las 12 del dia del inicio del dia
  	create(user: user, expires_at: DateTime.now + 12.hours, token: generate_token)
  end

  def self.generate_token
  	Devise.friendly_token.first(16)
  end

  private
  def send_mail
  	EmailLinkMailer.sign_in_mail(self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_links_controller.rb
class EmailLinksController < ApplicationController
  def new
  end

  def create
  	@email_link = EmailLink.generate(params[:email])

  	# si existe el usuario lo envia login pero con el mensaje q se envio un link a su correo
  	# si es nil, es porque el usuario no existe y debe reenviarlo a login
  	if @email_link
  		redirect_to new_user_session_path, notice: 'Revisa tu bandeja de correo para ingresar a tu cuenta con el link enviado'
  	else
  		redirect_to new_user_session_path, notice: 'No existe un usuario para dicho correo'
  	end
  end

  def validate
  	email_link = EmailLink.where(token: params[:token]).first
  	# si es nil el emial_link es q no existe el token o q ya expiero el token
  	unless email_link
  		return redirect_to new_user_session_path, notice: 'Link invàlido o ya expirò, intenta de nuevo'
  	end
  	# metodo de devise para iniciar sesion
  	# se envia el objecto y el tipo de objecto (User)
  	sign_in(email_link.user, scope: :user)
  	# solo se puede acceder al root_path si se inicio sesion
  	redirect_to root_path
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authenticate_user!
  
  def welcome
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_links_helper.rb
module EmailLinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/email_links/create.html.erb
<h1>EmailLinks#create</h1>
<p>Find me in app/views/email_links/create.html.erb</p>

app/views/email_links/new.html.erb
<h1>Sign up your account with a link in your email</h1>
<p>No password!. Tell us your email above</p>

<%= form_with url: send_link_path, method: :post do |f| %>
	<input type="text" name="email" placeholder="Your email" class="form-control">
	<input type="submit" value="Generate link" class="bt btn-info">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginLink</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/welcome.html.erb
<h1>Welcome</h1>
<p><%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>